name: drizzle_app
description: A weather forecast app being developed in Dart and Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_collection: '>=2.0.0 <5.0.0'
  built_value: ^7.1.0
  http: ^0.12.0+4
  geojson: ^0.9.1
  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator: ^7.0.9
  test: ^1.9.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
